const createTag = require("./create")
const deleteTag = require("./delete")
const userTag = require("./user")
const societyTag = require("./society")
const linkBox = require("./linkBox")
const destroyLinkBox = require("./destroyLinkBox")
const tagOnBox = require("./tagOnBox")
const linkRoom = require("./linkRoom")
const destroyLinkRoom = require("./destroyLinkRoom")

exports.createTag = createTag
exports.deleteTag = deleteTag
exports.userTag = userTag
exports.societyTag = societyTag
exports.linkBox = linkBox
exports.destroyLinkBox = destroyLinkBox
exports.tagOnBox = tagOnBox
exports.destroyLinkRoom = destroyLinkRoom
exports.linkRoom = linkRoom
