-- AlterTable
ALTER TABLE "Box" ALTER COLUMN "creation_date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creation_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Object" ALTER COLUMN "creation_date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creation_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Room" ALTER COLUMN "creation_date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creation_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "creation_date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creation_date" SET DATA TYPE TIMESTAMP(3);
